export const workExperience = [
  {
    company: "Cursor",
    role: "Senior Software Engineer",
    startDate: "2023-06",
    endDate: "Present",
    description: [
      "Leading development of AI-powered code editing features using LLMs",
      "Building and maintaining core IDE functionality in TypeScript/React",
      "Implementing real-time collaboration features and developer tools",
      "Contributing to product strategy and technical architecture decisions",
    ],
    location: "San Francisco, CA",
    logo: "/images/logos/cursor.png",
  },
  {
    company: "Freelance",
    role: "Software Engineering Consultant",
    startDate: "2023-01",
    endDate: "2023-06",
    description: [
      "Developed full-stack applications for various clients using modern tech stacks",
      "Implemented AI/ML solutions for process automation and data analysis",
      "Provided technical leadership and architecture consulting",
      "Built custom integrations with various APIs and cloud services",
    ],
    location: "Remote",
    logo: "/images/logos/freelance.png",
  },
  {
    company: "Salesforce",
    role: "Senior Software Engineer",
    startDate: "2021-03",
    endDate: "2022-12",
    description: [
      "Led development of key features for Einstein Analytics platform",
      "Built data visualization and analytics tools using React/TypeScript",
      "Improved performance and scalability of data processing pipelines",
      "Mentored junior engineers and contributed to technical design reviews",
    ],
    location: "San Francisco, CA",
    logo: "/images/logos/salesforce.png",
  },
  {
    company: "Apple",
    role: "Software Engineer",
    startDate: "2019-06",
    endDate: "2021-03",
    description: [
      "Developed internal tools for supply chain management",
      "Built and maintained React/Node.js applications",
      "Implemented automated testing and CI/CD pipelines",
      "Collaborated with cross-functional teams to deliver critical features",
    ],
    location: "Cupertino, CA",
    logo: "/images/logos/apple.png",
  },
];
